### ISSUE TITLE
No lib file in repo

### ISSUE THREAD

**Issue by Meisolsson** [spotify/android-auth#15]
Hi,

From the docs on https://developer.spotify.com/technologies/spotify-android-sdk/android-sdk-authentication-guide/. It says to download the repo as a .zip file and then get the .aar. Problem is that the .aar is non existent and you need to build it yourself, feels like a weird step.

**Comment by charlieCollins** [comment]
^ Need to update the guide to include that you need to build the auth lib yourself. Or, put the binary via the link the guide supplies.

**Comment by NeoLegends** [comment]
We're using this library inside of a Cordova app. Every time we make changes to the library, Cordova rebuilds this library, which takes quite a long time and thus slows down the development. A binary release would be much appreciated.

**Comment by charlieCollins** [comment]
@erdtman Can you copy the libs from the sample app into the release page? I know this is minor, but it would make the docs match what's really there and make the process a little easier on people just getting started.

**Comment by adstro** [comment]
Instead of making the .aar a separate download, it may be easier for the end user if the .aar was added to a repository like Maven Central, JCenter or jitpack.io so users can let Gradle do the work.

**Comment by bgermann** [comment]
I pull requested this repo including a fix for this issue, as it would enable jitpack.io to generate a binary: https://github.com/spotify/android-auth/pull/10

**Comment by bgermann** [comment]
Just for the record: you can use the library now by using jitpack: https://jitpack.io/#spotify/android-auth/9425c6a140 (current master version)

**Comment by ludik0** [comment]
Just in case anyone else tries to use the aar files @charlieCollins  mentioned.

You also need to use these lines in your build.gradle file:

`compile(name: 'spotify-android-auth-1.0.0', ext: 'aar')`
    `compile(name: 'spotify-player-24-noconnect-2.20b', ext: 'aar')`

**Comment by GarryMcKee** [comment]
Thanks for the jitpack link!

**Comment by hughrawlinson** [comment]
It looks like this was merged and fixed - please feel free to reopen this issue if I've misunderstood.
