### ISSUE TITLE
White web view while trying to authenticate with Spotify

### ISSUE THREAD

**Issue by aadithyb** [spotify/android-auth#17]
![spotify_sdk_bug](https://cloud.githubusercontent.com/assets/10493532/22314907/82c5d012-e318-11e6-8211-880b3f110fe5.png)

Steps to reproduce - 

1) Open sample app on Motorola Nexus 6 with/without spotify
2) Click login
3) Observe white screen

**Comment by aadithyabk** [comment]
Fixed this issue by using chrome custom tabs
