### ISSUE TITLE
No more slot available for my app

### ISSUE THREAD

**Issue by greencoppercompany** [spotify/android-auth#26]
**Description**

On my developer account I am not able to save my changes.
I'm trying to register one more Android Package Name and SHA1 Fingerprint. It's well added in list and displayed but nothing happened when I click on the save button.

**Steps to Reproduce**

Create an app in your developer portal
Add 64 Android Package Names and SHA1
Try to add one more and to save.
You will not be able to save your changes.

Thank you for your help!

**Comment by dloic** [comment]
Hi!

Any update on this one? It seems we're reaching some kinds of limit on the web form, not allowing us to add as many tuples (package name, sha1) as we want. We're integrating Spotify into many iOS and Android applications and we would like to avoid creating too many Spotify apps on dev portal.

Thanks for your help!

**Comment by hughrawlinson** [comment]
Hi! Yes, the number of apps are limited per client id, and the number of client ids is also limited. If you're running into issues with the limits, please reach out to [developer-support@spotify.com](mailto:developer-support@spotify.com), and we'll see if we can help. Please include details about why you're running into the limits, what kind of apps you're making, and whether or not you're a commercial entity.
