### ISSUE TITLE
What is the open source licence ?

### ISSUE THREAD

**Issue by munhra** [spotify/android-auth#45]
Hello guys thanks for a good job on the sdk, it saves me hours of hard work. I'm here to ask you guys what is the open source license, AGPL, GPL, LGPL, APACHE, MIT or other, that applies to the lib. I look inside document https://beta.developer.spotify.com/terms but I could not find it.

**Comment by arirawr** [comment]
Hi there! The license can be found here: https://github.com/spotify/android-auth/blob/master/LICENSE. Use of any Spotify Developer tools falls under our [Developer Terms of Service](https://developer.spotify.com/terms).
